### ISSUE TITLE
DefaultScheduler can cause persistent data loss, when block is restarted

### ISSUE THREAD

**Issue by xtenzo** [mesosphere/dcos-commons#175]
Persistent data can be lost if block is restarted after initial deployment, when `DefaultScheduler` is used. This happens only if scheduler was not restarted after the initial deployment.

Please see the test in https://github.com/xtenzo/dcos-commons/commit/737b1d113349951bcb72f0b67b1158524483b59f that reproduces this. If "Simulate scheduler restart block" is uncommented, then test passes.

When `Plan` is initialized for initial deployment from the `ServiceSpecification`, it does not contain any reservation IDs. During initial deployment reservation IDs are assigned, but they are not reflected in the plan. So when restart happens, a new task is started instead of the old one (which also involves `RESERVE` and `CREATE` operations), and soon after that cleaner `UNRESERVE`s and `DESTROY`s resources from the original task. However, after scheduler is restarted, `DefaultBlockFactory` uses `TaskInfo` from `StateStore` to create plan with reservation IDs assigned, so restart runs as expected.

**Comment by gabrielhartmann** [comment]
I'm not sure this isn't by design.  Restarting a block (now step) should redo the work it did before.  In this case, that's initial launch.  If you want to restart a Task, restarting the deployment block is not the way to do it.

The way to do it is [through this endpoint](https://github.com/mesosphere/dcos-commons/blob/master/sdk/scheduler/src/main/java/org/apache/mesos/scheduler/api/TaskResource.java#L154-L167) or equivalent implementation.

Then the RecoveryManager will relaunch using the same resources as expected.

**Comment by triclambert** [comment]
@xtenzo, please reopen if that did not answer your question.
